kas: fix typo correction
Remove extra space in front of meta-mediatek-demo section causing the
following build issue:

kas build kas/rity-demo.yml:kas/frag/ci.yml
'
2022-11-29 09:27:28 - INFO     - kas 3.1 started
2022-11-29 09:27:28 - INFO     - /tmp/build/543f317b/rity-manifest/kas$ git rev-parse --show-toplevel
2022-11-29 09:27:28 - INFO     - /tmp/build/543f317b/rity-manifest/kas$ git rev-parse --show-toplevel
2022-11-29 09:27:28 - INFO     - /tmp/build/543f317b/rity-manifest/kas/frag$ git rev-parse --show-toplevel
2022-11-29 09:27:28 - INFO     - adding SSH key
2022-11-29 09:27:28 - ERROR    - while parsing a block mapping
  in "/tmp/build/543f317b/rity-manifest/kas/include/deps.yml", line 5, column 3
expected <block end>, but found '<block mapping start>'
  in "/tmp/build/543f317b/rity-manifest/kas/include/deps.yml", line 54, column 4
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/kas/kas.py", line 165, in main
    sys.exit(kas(sys.argv[1:]))
  File "/usr/local/lib/python3.9/dist-packages/kas/kas.py", line 154, in kas
    plugin.run(args)
  File "/usr/local/lib/python3.9/dist-packages/kas/plugins/build.py", line 90, in run
    macro.run(ctx, args.skip)
  File "/usr/local/lib/python3.9/dist-packages/kas/libcmds.py", line 99, in run
    command.execute(ctx)
  File "/usr/local/lib/python3.9/dist-packages/kas/libcmds.py", line 349, in execute
    ctx.missing_repo_names = ctx.config.find_missing_repos()
  File "/usr/local/lib/python3.9/dist-packages/kas/config.py", line 75, in find_missing_repos
    self.handler.get_config(repos=repo_paths)
  File "/usr/local/lib/python3.9/dist-packages/kas/includehandler.py", line 266, in get_config
    cfgs, reps = _internal_include_handler(configfile,
  File "/usr/local/lib/python3.9/dist-packages/kas/includehandler.py", line 198, in _internal_include_handler
    (cfg, rep) = _internal_include_handler(includefile,
  File "/usr/local/lib/python3.9/dist-packages/kas/includehandler.py", line 172, in _internal_include_handler
    current_config = load_config(filename)
  File "/usr/local/lib/python3.9/dist-packages/kas/includehandler.py", line 64, in load_config
    config = yaml.safe_load(fds)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "/tmp/build/543f317b/rity-manifest/kas/include/deps.yml", line 5, column 3
expected <block end>, but found '<block mapping start>'
  in "/tmp/build/543f317b/rity-manifest/kas/include/deps.yml", line 54, column 4

Signed-off-by: Sean McGannon <smcgannon@baylibre.com>